### ISSUE TITLE
Whats about --single-transaction?

### ISSUE THREAD

**Issue by sumedia-webdesign** [kellerkinderDE/shopware6-database-dump#8]

**Comment by kleinmann** [comment]
Hi @sumedia-webdesign, I'm not sure I understand your question 🙂 Can you add some context?

**Comment by sumedia-webdesign** [comment]
Hi, sure.

I recently noticed that the database in MySQL seems to lock tables without --single-transaction. This disrupted the operation of the website. Maxcluster told me this. I still don't know why that is the case. Because I think the data synchronicity is gone anyway as soon as the file is saved. But no idea.
That's why I ask.

Without --single-transaction it disrupts the operation of live databases.

**Comment by kleinmann** [comment]
Hi @sumedia-webdesign, since we're already using `--single-transaction` in this script, I'm still not sure what you're getting at 🙂
`--single-transaction` should correctly skip table locks as per the [MySQL documentation](https://dev.mysql.com/doc/refman/8.2/en/mysqldump.html#option_mysqldump_single-transaction).

**Comment by sumedia-webdesign** [comment]
Oh, then i must be redirected to an older code by google.
But History say no. Maybe, i didn't see that.

**Comment by kleinmann** [comment]
No worries 🙂 I'll close the issue, then.
